ALTER TABLE "CommitLite" ADD COLUMN "changedFiles" TEXT[] DEFAULT ARRAY[]::TEXT[];

ALTER TABLE "StorageQuota" ALTER COLUMN "maxRepoBytes" SET DEFAULT 209715200;
ALTER TABLE "StorageQuota" ALTER COLUMN "maxFileBytes" SET DEFAULT 10485760;
ALTER TABLE "StorageQuota" ALTER COLUMN "maxFilesPerRepo" SET DEFAULT 1000;
